- name: type1 variable
  hosts: localhost 
  vars:
    PERSON: "Mahesh"
    WISHES: "Good Morning"
  tasks: 
    - name: Print variables
      ansible.builtin.debug:
        msg: "Hello {{ PERSON }}, {{ WISHES }}! Have a nice day!"